### ISSUE TITLE
Memory usage constantly increasing

### ISSUE THREAD

**Issue by lucasgiusti** [zeebe-io/zeebe-client-node-js#174] opened 2020-08-24 22:59 UTC
Hello, could you help me?

I'm using "zeebe-node" in a docker container and I'm having problems.
The memory used by my application is constantly increasing until it crashes.
Did you have any problems with this when using this lib?

**Note: The memory increase occurs even though there are no tasks for workers.**

This is the memory usage constantly increasing:
<img width="1629" alt="Captura de Tela 2020-08-24 às 19 06 52" src="https://user-images.githubusercontent.com/5943223/91104046-51ee7200-e643-11ea-82da-c528b17cb013.png">

This is my code:
file src/envio-consulta-produto/index.js:
<img width="1058" alt="Captura de Tela 2020-08-24 às 19 08 38" src="https://user-images.githubusercontent.com/5943223/91104071-65014200-e643-11ea-9b91-08faf10054bb.png">

files src/workers/*.js:
<img width="826" alt="Captura de Tela 2020-08-24 às 19 09 22" src="https://user-images.githubusercontent.com/5943223/91104180-a0037580-e643-11ea-9dee-41d4d4d6180c.png">

**Comment by jwulf** [comment] 2020-08-25 18:11
Hi @lucasgiusti,

I can't see anything in your code that would cause a memory leak. I have applications running for months with the zeebe-node client with no leaks.

It looks like you can see a measurable increase in a relatively short period of time. Let me make a small project and test it.

**Comment by jwulf** [comment] 2020-08-25 18:31
Here is my code:

```
import { ZBClient, Duration } from "zeebe-node";
import { config } from "dotenv";
import got from "got";

config();

const zbc = new ZBClient();

zbc.createWorker("get-time", async (job, complete) => {
  const time = await got("https://json-api.joshwulf.com/time").json();
  console.log(time);
  complete.success({ time });
});

zbc.createWorker("make-greeting", (job, complete) => {
  const { greeting } = job.customHeaders;
  const { name } = job.variables;
  const say = `${greeting} ${name}`;
  console.log(say);
  complete.success({ say });
});

setInterval(() => {
  console.log(Date.now().toLocaleString(), process.memoryUsage());
}, Duration.milliseconds.from(Duration.minutes.of(5)));

```

I will run this with the 0.24.0 release for a few hours and report back what I see.

**Comment by lucasgiusti** [comment] 2020-08-25 18:45
Nice @jwulf, 
thank you so much for your help!

**Comment by jwulf** [comment] 2020-08-25 21:36
After three hours there is no memory increase. Could it be somewhere else in your code? 

Can you make a minimum reproducer?

**Comment by lucasgiusti** [comment] 2020-08-26 00:02
My code is just this.
The difference cannot be the settings below ?
{ longPoll: Duration.minutes.of(10) }
{ timeout: Duration.minutes.of(5) }

**Comment by jwulf** [comment] 2020-08-26 13:13
Nope. Here is the result with those settings:

```
Wed, 26 Aug 2020 10:27:21 GMT Memory: 168.0M
Wed, 26 Aug 2020 10:32:21 GMT Memory: 168.0M
Wed, 26 Aug 2020 10:37:21 GMT Memory: 152.9M
Wed, 26 Aug 2020 10:42:21 GMT Memory: 131.9M
Wed, 26 Aug 2020 10:47:21 GMT Memory: 131.9M
Wed, 26 Aug 2020 10:52:21 GMT Memory: 131.9M
Wed, 26 Aug 2020 10:57:21 GMT Memory: 132.6M
Wed, 26 Aug 2020 11:02:21 GMT Memory: 132.6M
Wed, 26 Aug 2020 11:07:21 GMT Memory: 132.3M
Wed, 26 Aug 2020 11:12:21 GMT Memory: 132.8M
Wed, 26 Aug 2020 11:17:21 GMT Memory: 132.9M
Wed, 26 Aug 2020 11:22:21 GMT Memory: 133.0M
Wed, 26 Aug 2020 11:27:21 GMT Memory: 133.8M
Wed, 26 Aug 2020 11:32:21 GMT Memory: 133.3M
Wed, 26 Aug 2020 11:37:21 GMT Memory: 134.3M
Wed, 26 Aug 2020 11:42:21 GMT Memory: 134.0M
Wed, 26 Aug 2020 11:47:21 GMT Memory: 134.6M
Wed, 26 Aug 2020 11:52:21 GMT Memory: 135.6M
Wed, 26 Aug 2020 11:57:21 GMT Memory: 135.9M
Wed, 26 Aug 2020 12:02:21 GMT Memory: 136.4M
Wed, 26 Aug 2020 12:07:21 GMT Memory: 136.5M
Wed, 26 Aug 2020 12:12:21 GMT Memory: 137.4M
Wed, 26 Aug 2020 12:17:21 GMT Memory: 137.9M
Wed, 26 Aug 2020 12:22:21 GMT Memory: 138.1M
Wed, 26 Aug 2020 12:27:21 GMT Memory: 138.8M
Wed, 26 Aug 2020 12:32:21 GMT Memory: 138.4M
Wed, 26 Aug 2020 12:37:21 GMT Memory: 139.1M
Wed, 26 Aug 2020 12:42:21 GMT Memory: 139.2M
Wed, 26 Aug 2020 12:47:21 GMT Memory: 140.0M
Wed, 26 Aug 2020 12:52:21 GMT Memory: 142.1M
Wed, 26 Aug 2020 12:57:21 GMT Memory: 142.1M
Wed, 26 Aug 2020 13:02:21 GMT Memory: 142.5M
Wed, 26 Aug 2020 13:07:21 GMT Memory: 110.4M
```

**Comment by jwulf** [comment] 2020-08-26 13:13
Run my code in your environment, and see if you can reproduce it.

Then add in additional parts of your code, until you isolate what it is.

Alternatively, if you can create a minimal reproducer that demonstrates it, I can run that.

**Comment by lucasgiusti** [comment] 2020-08-26 13:50
Ok,
I will do this test and comment here.
Thank you!

**Comment by lucasgiusti** [comment] 2020-08-26 21:36
Hi,
I did the example below and the memory increase occurred:

`'use strict';

const { ZBClient, Duration } = require('zeebe-node');
const zbc = new ZBClient(process.env.ZEEBE_ADDRESS);
const Dayjs = require('dayjs');

zbc.createWorker("parser-preco-to-gaia-v1", (job, complete) => {
  const { greeting } = job.customHeaders;
  const { name } = job.variables;
  const say = `${greeting} ${name}`;
  console.log(say);
  complete.success({ say });
});

setInterval(() => {
  console.log(
    Dayjs().toString(),
    "Memory: " + (process.memoryUsage().rss / 1024 / 1024).toFixed(1) + "M"
  );
}, Duration.milliseconds.from(Duration.minutes.of(5)));`

`Wed, 26 Aug 2020 17:35:53 GMT Memory: 77.7M
Wed, 26 Aug 2020 17:40:53 GMT Memory: 78.3M
Wed, 26 Aug 2020 17:45:53 GMT Memory: 80.4M
Wed, 26 Aug 2020 17:50:53 GMT Memory: 81.9M
Wed, 26 Aug 2020 17:55:53 GMT Memory: 84.3M
Wed, 26 Aug 2020 18:00:53 GMT Memory: 85.7M
Wed, 26 Aug 2020 18:05:53 GMT Memory: 85.6M
Wed, 26 Aug 2020 18:10:53 GMT Memory: 85.9M
Wed, 26 Aug 2020 18:15:53 GMT Memory: 86.6M
Wed, 26 Aug 2020 18:20:53 GMT Memory: 86.6M
Wed, 26 Aug 2020 18:25:53 GMT Memory: 87.3M
Wed, 26 Aug 2020 18:30:53 GMT Memory: 87.3M
Wed, 26 Aug 2020 18:35:53 GMT Memory: 88.3M
Wed, 26 Aug 2020 18:40:53 GMT Memory: 88.1M
Wed, 26 Aug 2020 18:45:53 GMT Memory: 89.0M
Wed, 26 Aug 2020 18:50:53 GMT Memory: 87.7M
Wed, 26 Aug 2020 18:55:53 GMT Memory: 88.0M
Wed, 26 Aug 2020 19:00:53 GMT Memory: 88.3M
Wed, 26 Aug 2020 19:05:53 GMT Memory: 88.9M
Wed, 26 Aug 2020 19:10:53 GMT Memory: 89.3M
Wed, 26 Aug 2020 19:15:53 GMT Memory: 88.7M
Wed, 26 Aug 2020 19:20:53 GMT Memory: 89.2M
Wed, 26 Aug 2020 19:25:53 GMT Memory: 90.0M
Wed, 26 Aug 2020 19:30:53 GMT Memory: 89.1M
Wed, 26 Aug 2020 19:35:53 GMT Memory: 89.9M
Wed, 26 Aug 2020 19:40:53 GMT Memory: 90.1M
Wed, 26 Aug 2020 19:45:53 GMT Memory: 90.5M
Wed, 26 Aug 2020 19:50:53 GMT Memory: 90.1M
Wed, 26 Aug 2020 19:55:53 GMT Memory: 90.9M
Wed, 26 Aug 2020 20:00:53 GMT Memory: 91.0M
Wed, 26 Aug 2020 20:05:53 GMT Memory: 91.2M
Wed, 26 Aug 2020 20:10:53 GMT Memory: 91.2M
Wed, 26 Aug 2020 20:15:53 GMT Memory: 91.6M
Wed, 26 Aug 2020 20:20:53 GMT Memory: 92.1M
Wed, 26 Aug 2020 20:25:53 GMT Memory: 91.0M
Wed, 26 Aug 2020 20:30:53 GMT Memory: 91.7M
Wed, 26 Aug 2020 20:35:53 GMT Memory: 91.8M
Wed, 26 Aug 2020 20:40:53 GMT Memory: 91.7M
Wed, 26 Aug 2020 20:45:53 GMT Memory: 92.5M
Wed, 26 Aug 2020 20:50:53 GMT Memory: 92.4M
Wed, 26 Aug 2020 20:55:53 GMT Memory: 92.4M
Wed, 26 Aug 2020 21:00:53 GMT Memory: 92.5M
Wed, 26 Aug 2020 21:05:53 GMT Memory: 92.9M
Wed, 26 Aug 2020 21:10:53 GMT Memory: 92.8M
Wed, 26 Aug 2020 21:15:53 GMT Memory: 93.8M
Wed, 26 Aug 2020 21:20:53 GMT Memory: 93.9M
Wed, 26 Aug 2020 21:25:53 GMT Memory: 94.0M
Wed, 26 Aug 2020 21:30:53 GMT Memory: 94.4M`

Which docker image did you use? I used the image "node: 13.5.0"

**Comment by lucasgiusti** [comment] 2020-08-30 19:28
Hi @jwulf,
Can you run the code below in a container with a docker image "FROM node: 13.5.0" for a few hours?
Thus, I managed to reproduce the error with the code below:

```
'use strict';

const { ZBClient, Duration } = require('zeebe-node');
const zbc = new ZBClient(process.env.ZEEBE_ADDRESS);
const Dayjs = require('dayjs');

zbc.createWorker("parser-preco-to-gaia-v1", (job, complete) => {
  const { greeting } = job.customHeaders;
  const { name } = job.variables;
  const say = `${greeting} ${name}`;
  console.log(say);
  complete.success({ say });
});

setInterval(() => {
  console.log(
    Dayjs().toString(),
    "Memory: " + (process.memoryUsage().rss / 1024 / 1024).toFixed(1) + "M"
  );
}, Duration.milliseconds.from(Duration.minutes.of(5)));
```

**Comment by lucasgiusti** [comment] 2020-08-31 14:40
These are two files to compare the memory change in Google Chrome. But I don't know the "node-zeebe" code to do an analysis:
[heapsnapshot files](https://drive.google.com/drive/folders/152_6XuEq1EvE-B-esEBp9yUuqF3Ub-Hf?usp=sharing)

**Comment by jwulf** [comment] 2020-09-01 07:08
Can you make a repo with an MRE in it? If you can do that, then I can clone it locally and run `docker-compose up`, and we'll know that we are running the exact same code.

I'm keen to reproduce this and figure it out.

**Comment by lucasgiusti** [comment] 2020-09-01 21:28
Nice,
I will create and post right here.

**Comment by lucasgiusti** [comment] 2020-09-08 19:22
Hi,

My last execution return this data:
<img width="1646" alt="Captura de Tela 2020-09-08 às 16 06 30" src="https://user-images.githubusercontent.com/5943223/92518658-129d5500-f1ef-11ea-84b3-7ddbf23182ba.png">

<img width="1646" alt="Captura de Tela 2020-09-08 às 16 06 51" src="https://user-images.githubusercontent.com/5943223/92518676-17fa9f80-f1ef-11ea-973f-bdfa13244198.png">

The code is available in:
https://github.com/lucasgiusti/test-zeebe

**See Readme.md**

Tks @jwulf .

**Comment by jwulf** [comment] 2020-09-16 09:38
Yes, I reproduced it with this. Over 12 hours, it went from 22MB to 44MB memory usage.

**Comment by lucasgiusti** [comment] 2020-09-16 19:18
Do you know how to identify memory problems in nodejs.snapshot files?
I tried, but I can't.

@jwulf

**Comment by soares-luan** [comment] 2020-09-28 19:22
Hi @jwulf could u understand why the process is consuming so much memory that it stops the docker?
I work with @lucasgiusti on that case

**Comment by jwulf** [comment] 2020-10-16 07:23
I think this is a Garbage Collector issue in Node 13. 

The odd numbered Node releases are development versions. 12 and 14 are production releases. 

On Node 12 on my laptop, and if I rebuild this container with Node 14.2.0, I don't see the memory leak issue.

**Comment by jwulf** [comment] 2020-10-23 01:22
Closing this for now - if you still see the issue with v0.25.0 of the client on Node 12 or 14, let me know.

**Closed by jwulf** 2020-10-23 01:22 UTC
